words = [
    "argmin",
    "backprop",
    "ewton",
    "momentums",
    "naphat",
    "oment",
    "orthogonalization",
    "orthogonalize",
    "rthogonalized",
    "svd",
]
ignore_paths = [
    "**/*.py",
]
