version: 3

tasks:
  run:
    desc: Run the main file
    silent: true
    dir: src
    env:
      PYTHONPATH: .
    cmds:
      - uv run main.py

  run.watch:
    desc: Run and watch for changes (requires watchexec)
    dir: src
    cmds:
      - watchexec --exts py task run

  check-format:
    desc: Perform static checks and run formatter
    dir: src
    cmds:
      - uv run ty check
      - uv run ruff check
      - uv run ruff format

  typst.compile:
    desc: Compile the presentation
    cmds:
      - typst compile presentation/main.typ

  typst.watch:
    desc: Watch and recompile presentation on changes
    cmds:
      - typst watch presentation/main.typ

  typst.check:
    desc: Check that the presentation compiles without errors
    silent: true
    cmds:
      - typst compile -f pdf presentation/main.typ /dev/null
